# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9997ee1aa9a35d6e7cc535a1cfe6742bb82e7dee5ce28d72a4a6fb14f0a4a5c3396628c1c9f3102a79c7453d93596bdbd4aa42c1fb77bcebf409f87c1b0c40

test:
  secret_key_base: f1f7c263a675b822ea411f211941edf5056f41641c103f09abc31401c51e9887313c2e21d467daa49c465824d9ba6c736e352c5a667ec9295e39e5bc2f5381d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
